[package]
name = "domrs"
version = "0.0.2"
authors = ["Dariusz Depta <code@senees.de>"]
description = "DOM Builder and Serializer"
documentation = "https://docs.rs/domrs"
repository = "https://github.com/senees/domrs.git"
license = "MIT"
edition = "2021"

[dependencies]
